# -----------------------------------------------------------------------------
# Project Name: Neural Splines
# File: spline_conv.py
#
# This file is part of a project licensed under the GNU Affero General Public
# License. See the project LICENSE for the full text.
# -----------------------------------------------------------------------------

"""Convolutional layer whose kernels are generated by spline interpolation.

Where the spline prior belongs
------------------------------
A convolution weight has shape ``(out_channels, in_channels, kH, kW)``.
Interpolation imposes smoothness along whichever axes it spans, so it is only
appropriate where neighbouring indices are actually related:

* **Spatial axes (kH, kW)** -- genuine image space. Neighbouring taps of a
  learned filter really are related, and trained filters are frequently smooth
  (edge and blob detectors, Gabor-like structure). A spline prior is a good
  match here.
* **Channel axes** -- arbitrary ordering. A network is invariant to permuting
  its channels, so channel *c* and channel *c+1* have no reason to resemble one
  another. This layer deliberately does **not** interpolate across channels.

That distinction is not a matter of taste. Applying a spline across the
arbitrarily-ordered axis of a fully connected layer measurably costs about ten
accuracy points relative to spending the same budget on the meaningful axis
(see ``experiments/ATOMICS.md``), and fitting a spline to a trained weight
matrix along that axis fails outright.

When this saves parameters
--------------------------
A ``cp_h x cp_w`` grid replaces a ``kH x kW`` kernel per channel pair, so the
saving is ``(kH*kW) / (cp_h*cp_w)``. Cubic interpolation needs at least four
control points per axis, so there is nothing to gain below a 5x5 kernel and the
layer is most useful for large kernels -- 7x7, 9x9, 11x11 -- where a smooth
filter is cheap to describe and expensive to store tap by tap.
"""

from __future__ import annotations

from typing import Tuple, Union

import torch
import torch.nn as nn
import torch.nn.functional as F

_Size = Union[int, Tuple[int, int]]


def _pair(value: _Size) -> Tuple[int, int]:
    if isinstance(value, int):
        return value, value
    a, b = value
    return int(a), int(b)


class SplineConv2d(nn.Module):
    """A 2-D convolution whose kernels are interpolated from control points.

    Mirrors :class:`torch.nn.Conv2d`'s signature. Instead of storing
    ``out_channels x in_channels x kH x kW`` weights, it stores a
    ``cp_h x cp_w`` grid per channel pair and expands it with bicubic
    interpolation on each forward pass.

    Parameters
    ----------
    in_channels, out_channels : int
        As for :class:`torch.nn.Conv2d`.
    kernel_size : int or (int, int)
        Size of the kernel the control points are expanded to.
    cp_h, cp_w : int, optional
        Control points along each spatial axis. ``cp_w`` defaults to ``cp_h``.
        Both must be at least 4 for bicubic interpolation.
    stride, padding, dilation, groups, bias
        As for :class:`torch.nn.Conv2d`.

    Raises
    ------
    ValueError
        If fewer than four control points are requested on either axis, if
        ``in_channels`` is not divisible by ``groups``, or if the grid is no
        smaller than the kernel it would expand to (which would store more
        parameters than a dense convolution, defeating the purpose).
    """

    def __init__(
        self,
        in_channels: int,
        out_channels: int,
        kernel_size: _Size,
        cp_h: int = 4,
        cp_w: int | None = None,
        stride: _Size = 1,
        padding: _Size = 0,
        dilation: _Size = 1,
        groups: int = 1,
        bias: bool = True,
    ) -> None:
        super().__init__()
        cp_w = cp_h if cp_w is None else cp_w
        if cp_h < 4 or cp_w < 4:
            raise ValueError(
                "cp_h and cp_w must be at least 4 for bicubic interpolation"
            )
        if in_channels % groups != 0 or out_channels % groups != 0:
            raise ValueError("in_channels and out_channels must be divisible by groups")

        self.kernel_size = _pair(kernel_size)
        if cp_h * cp_w >= self.kernel_size[0] * self.kernel_size[1]:
            raise ValueError(
                f"a {cp_h}x{cp_w} control grid is not smaller than the "
                f"{self.kernel_size[0]}x{self.kernel_size[1]} kernel it expands to, "
                f"so it would store more parameters than nn.Conv2d. Use a larger "
                f"kernel or fewer control points."
            )

        self.in_channels = in_channels
        self.out_channels = out_channels
        self.cp_h = cp_h
        self.cp_w = cp_w
        self.stride = _pair(stride)
        self.padding = _pair(padding)
        self.dilation = _pair(dilation)
        self.groups = groups

        # One control grid per channel pair. The channel axes are NOT
        # interpolated -- see the module docstring.
        #
        # Interpolation is linear, so it rescales the standard deviation of the
        # control points by a fixed factor. Initialising the grid directly at
        # the Kaiming scale therefore produces a *kernel* whose scale is wrong
        # -- measured at 1.48x too large for a 5x5 grid on a 9x9 kernel. Divide
        # it out so the interpolated kernel lands at the intended scale.
        # Target nn.Conv2d's own default so this is a drop-in replacement:
        # kaiming_uniform_(a=sqrt(5)) has bound sqrt(1/fan_in) and therefore
        # standard deviation sqrt(1/(3*fan_in)).
        fan_in = (in_channels // groups) * self.kernel_size[0] * self.kernel_size[1]
        target_std = (1.0 / (3.0 * fan_in)) ** 0.5
        self.control_points = nn.Parameter(
            torch.randn(out_channels, in_channels // groups, cp_h, cp_w)
            * (target_std / self._interpolation_gain())
        )
        self.bias: nn.Parameter | None
        if bias:
            self.bias = nn.Parameter(torch.zeros(out_channels))
        else:
            self.register_parameter("bias", None)

    def _interpolation_gain(self) -> float:
        """Factor by which interpolation scales the control points' std.

        Bicubic interpolation is a fixed linear map ``kernel = A C B^T``, so for
        i.i.d. control points the kernel's variance is scaled by the row norms
        of ``A`` and ``B``. Computed once at construction rather than assumed.
        """
        def axis(n_cp: int, n_out: int) -> torch.Tensor:
            identity = torch.eye(n_cp)
            return F.interpolate(
                identity.unsqueeze(0).unsqueeze(0), size=(n_out, n_cp),
                mode="bicubic", align_corners=True,
            ).squeeze(0).squeeze(0)

        a = axis(self.cp_h, self.kernel_size[0]).pow(2).sum(dim=1).mean()
        b = axis(self.cp_w, self.kernel_size[1]).pow(2).sum(dim=1).mean()
        return float((a * b).sqrt())

    def _interpolate_kernel(self) -> torch.Tensor:
        """Expand the control grids into a dense ``(out, in/groups, kH, kW)`` kernel."""
        o, i, h, w = self.control_points.shape
        # F.interpolate treats the leading two axes as batch and channel, so
        # every channel pair is expanded independently and none of them are
        # mixed together.
        flat = self.control_points.reshape(o * i, 1, h, w)
        dense = F.interpolate(
            flat, size=self.kernel_size, mode="bicubic", align_corners=True
        )
        return dense.reshape(o, i, *self.kernel_size)

    def forward(self, input: torch.Tensor) -> torch.Tensor:
        return F.conv2d(
            input,
            self._interpolate_kernel(),
            self.bias,
            self.stride,
            self.padding,
            self.dilation,
            self.groups,
        )

    def to_dense_conv(self) -> nn.Conv2d:
        """Return an equivalent :class:`torch.nn.Conv2d` with fixed weights.

        Removes the per-forward interpolation once the control points are no
        longer being trained, exactly as
        :meth:`neural_splines.SplineLinear.to_dense_linear` does.
        """
        conv = nn.Conv2d(
            self.in_channels,
            self.out_channels,
            self.kernel_size,
            stride=self.stride,
            padding=self.padding,
            dilation=self.dilation,
            groups=self.groups,
            bias=self.bias is not None,
        )
        conv.weight.data = self._interpolate_kernel().detach().clone()
        if self.bias is not None and conv.bias is not None:
            conv.bias.data = self.bias.detach().clone()
        return conv

    def parameter_saving(self) -> float:
        """Ratio of dense-convolution weights to stored control points."""
        dense = (
            self.out_channels
            * (self.in_channels // self.groups)
            * self.kernel_size[0]
            * self.kernel_size[1]
        )
        return dense / self.control_points.numel()

    def extra_repr(self) -> str:
        return (
            f"{self.in_channels}, {self.out_channels}, "
            f"kernel_size={self.kernel_size}, cp=({self.cp_h}, {self.cp_w}), "
            f"stride={self.stride}, padding={self.padding}, "
            f"saving={self.parameter_saving():.1f}x"
        )
